// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  datasource: {
    // Same default as `src/lib/env.ts`, repeated rather than imported: this file is
    // loaded by the Prisma CLI (via `postinstall`), outside Next's module graph and
    // its `@/` aliases, so it cannot read the app's env schema. Prisma's own
    // `env("DATABASE_URL")` helper *throws* when the variable is unset, which made
    // `npm install` fail on a clean clone before anyone could copy `.env.example`.
    // Falling back here keeps the repo installable with no `.env` at all.
    //
    // Relative `file:` paths resolve from the project root, same as the runtime
    // adapter's cwd — so migrations and the app hit the same file.
    url: process.env.DATABASE_URL ?? "file:./prisma/dev.db",
  },
});
