// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  datasource: {
    // Relative `file:` paths here resolve from the project root, same as the
    // runtime adapter's cwd — so migrations and the app hit the same file.
    url: env("DATABASE_URL"),
  },
});
